In [4]:
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from IPython.display import Image  
 

from sklearn import metrics
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import train_test_split
#X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.30)#test and train division
import statsmodels.api as sm
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

from sklearn.neural_network import MLPClassifier

In [5]:
df = pd.read_csv('modstudent.csv')
df.head()

continue_drop student_id  gender  caste  mathematics_marks  english_marks  \
0              0     s00001       2      3              0.409          0.514   
1              0     s00002       2      2              0.290          0.512   
2              0     s00003       2      1              0.602          0.666   
3              0     s00004       2      2              0.378          0.526   
4              0     s00005       2      1              0.536          0.614   

   science_marks  science_teacher  languages_teacher  guardian  internet  \
0          0.409                6                  0         2         1   
1          0.290                4                  7         2         1   
2          0.602                4                  2         2         0   
3          0.378                8                  7         2         1   
4          0.536                9                  4         0         1   

   school_id  total_students  total_toilets  establishment_year  
0        310             262           28.0              1985.0  
1        328             356           14.0              1943.0  
2        322             179            8.0              1955.0  
3        305             354           86.0              1986.0  
4        360             273            2.0              1995.0

In [6]:
import statsmodels.api as sm
from sklearn.preprocessing import StandardScaler
scale = StandardScaler()
#this is for common range
X = df[['gender', 'caste', 'mathematics_marks','english_marks', 'science_marks', 'science_teacher','languages_teacher', 'guardian', 'internet', 'total_students', 'total_toilets', 'establishment_year']]
y=df['continue_drop']
est = sm.OLS(y, X).fit()
est.summary()


<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:          continue_drop   R-squared (uncentered):                   0.077
Model:                            OLS   Adj. R-squared (uncentered):              0.076
Method:                 Least Squares   F-statistic:                              142.1
Date:                Mon, 28 Aug 2023   Prob (F-statistic):                   1.08e-315
Time:                        23:48:03   Log-Likelihood:                          2704.9
No. Observations:               18762   AIC:                                     -5388.
Df Residuals:                   18751   BIC:                                     -5302.
Df Model:                          11                                                  
Covariance Type:            nonrobust                                                  
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
gender                 0.0107      0.003      3.281      0.001       0.004       0.017
caste                 -0.0129      0.002     -6.553      0.000      -0.017      -0.009
mathematics_marks     -0.0319      0.005     -6.977      0.000      -0.041      -0.023
english_marks          0.1162      0.011     10.412      0.000       0.094       0.138
science_marks         -0.0319      0.005     -6.977      0.000      -0.041      -0.023
science_teacher        0.0109      0.001     17.364      0.000       0.010       0.012
languages_teacher     -0.0014      0.001     -2.624      0.009      -0.002      -0.000
guardian              -0.0026      0.003     -0.995      0.320      -0.008       0.003
internet               0.0347      0.004      8.045      0.000       0.026       0.043
total_students     -2.762e-06   1.22e-05     -0.226      0.821   -2.67e-05    2.12e-05
total_toilets        6.28e-05   7.56e-05      0.831      0.406   -8.53e-05       0.000
establishment_year -1.759e-05   5.62e-06     -3.131      0.002   -2.86e-05   -6.58e-06
==============================================================================
Omnibus:                    15127.354   Durbin-Watson:                   2.079
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           228837.695
Skew:                           4.052   Prob(JB):                         0.00
Kurtosis:                      18.068   Cond. No.                     3.55e+19
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[3] The smallest eigenvalue is 5.72e-29. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [7]:
X = df[['gender', 'caste', 'mathematics_marks','english_marks', 'science_marks', 'science_teacher','languages_teacher', 'guardian','internet']]
y=df['continue_drop']

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
model1 = tree.DecisionTreeClassifier(max_leaf_nodes=5,random_state=0)

#mode=lKNeighborsClassifier(n_neighbors=5,
#                        n_jobs=-1)
model3=XGBClassifier(random_state=0, n_jobs=-1, learning_rate=0.1, 
                  n_estimators=5,max_depth=5)
model4= RandomForestClassifier(n_estimators = 3,random_state= 0,verbose=2,n_jobs=-1,max_depth=3)
model5 = MLPClassifier(solver='sgd', hidden_layer_sizes=(5, 3), random_state=0,activation='logistic',learning_rate='invscaling')
models= [model1,model3,model4,model5]

In [9]:
model1 = model1.fit(X_train,y_train)
model5=model5.fit(X_train,y_train)
model3=model3.fit(X_train,y_train)
model4=model4.fit(X_train,y_train)


result1 = model1.predict(X_test)
result5= model5.predict(X_test)
result3=model3.predict(X_test)
result4= model4.predict(X_test)

building tree 1 of 3building tree 2 of 3

building tree 3 of 3


[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 24 concurrent workers.
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:    0.0s finished
[Parallel(n_jobs=3)]: Using backend ThreadingBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done   3 out of   3 | elapsed:    0.0s finished


In [10]:
import pickle
with open('model1.pkl', 'wb') as file:  
    pickle.dump(model1, file)
with open('model3.pkl', 'wb') as file:  
    pickle.dump(model3, file)
with open('model4.pkl', 'wb') as file:  
    pickle.dump(model4, file)
with open('model5.pkl', 'wb') as file:  
    pickle.dump(model5, file)


In [11]:
def mode (A,B,C,D):
    tzero = 0
    tone=0
    n= len(A)
    results=[]
    for i in range(0,n):
        one = 0
        zero = 0
        if(A[i]==0):
            zero = zero+1
        if(A[i]==1):
            one = one +1
        if(B[i]==0):
            zero = zero+1
        if(C[i]==0):
            zero = zero+1
        if(B[i]==1):
            one = one +1
        if(C[i]==1):
            one = one +1
        if(D[i]==0):
            zero = zero+1
        if(D[i]==1):
            one = one +1
        if(zero>one):
            results.append(0)
            tzero=tzero+1
        if(one>zero):
            results.append(1)
            tone=tone+1
        if(one == zero):
            if(tzero>tone):
                results.append(0)
                tzero=tzero+1
            else:
                results.append(1)
                tone=tone+1
    return results
def find(A):
    resul = []
    n = len(A)
    for i in range (0,n):
        if A[i]==1:
            resul.append(i)
    return resul
def compare(F,S):
    n = len(F)
    count = float(0)
    for i in range(0,n):
        if(F[i]==S[i]):
            count = count+1
        accu = float(count/n)
    return accu

In [12]:
results = mode(result1,result3,result4,result5)
test =np.array(y_test)
100*compare(results,test)

95.47029043431921

In [13]:
#https://mlfromscratch.com/model-stacking-explained/#/
#https://towardsdatascience.com/automate-stacking-in-python-fc3e7834772e

In [14]:
ft1=model1.feature_importances_
ft3=model3.feature_importances_
ft4=model4.feature_importances_

In [15]:
ft1

array([0.        , 0.        , 0.        , 0.87264968, 0.        ,
       0.12735032, 0.        , 0.        , 0.        ])

In [16]:
ft3

array([0.0127332 , 0.13360037, 0.19633858, 0.29607132, 0.        ,
       0.15519686, 0.06591616, 0.02204587, 0.11809755], dtype=float32)

In [17]:
ft4

array([0.        , 0.        , 0.24133008, 0.60052244, 0.08916948,
       0.05864004, 0.        , 0.        , 0.01033796])

In [18]:
ind = np.argsort(ft1)
ind = ind[-2:]
clas=X_train.columns
lis = ['Decision tree']
for i in ind:
    lis.append(clas[i])
mft1 = lis
mft1

['Decision tree', 'science_teacher', 'english_marks']

In [19]:
ind3 = np.argsort(ft3)
ind3 = ind3[-4:]
clas=X_train.columns
lis3 = ['XGB']
for i in ind3:
    lis3.append(clas[i])
mft3 = lis3

mft3

['XGB', 'caste', 'science_teacher', 'mathematics_marks', 'english_marks']

In [20]:
ind = np.argsort(ft4)
ind = ind[-4:]
clas=X_train.columns
lis = ["Random Forest"]
for i in ind:
    lis.append(clas[i])
mft4 = lis
mft4

['Random Forest',
 'science_teacher',
 'science_marks',
 'mathematics_marks',
 'english_marks']

In [21]:
dat=[mft1,mft3,mft4]
dat = pd.DataFrame(dat)
dat

0                1                2                  3  \
0  Decision tree  science_teacher    english_marks               None   
1            XGB            caste  science_teacher  mathematics_marks   
2  Random Forest  science_teacher    science_marks  mathematics_marks   

               4  
0           None  
1  english_marks  
2  english_marks

In [22]:
dat.to_csv(r'features.csv',header=True,index=None)

In [23]:
#inserting and interpretting dataset

In [24]:
def guess (dataset):
    ids=[]
    A = model1.predict(dataset)
    B = model5.predict(dataset)
    C =model3.predict(dataset)
    D = model4.predict(dataset)
    results = mode(A,B,C,D)
    index = find(results)
    for i in index :
        ids.append(df['student_id'][i])
    ids=pd.DataFrame(ids)
    ids.to_csv(r'Drop_Student_list.csv',header=True,index=None)

In [25]:
X_test

gender  caste  mathematics_marks  english_marks  science_marks  \
13057       1      3              0.562          0.709          0.562   
3236        1      2              0.768          0.755          0.768   
14942       1      2              0.686          0.830          0.686   
1586        2      2              0.586          0.648          0.586   
5455        1      2              0.485          0.520          0.485   
...       ...    ...                ...            ...            ...   
5750        2      3              0.684          0.848          0.684   
13338       1      4              0.999          0.745          0.999   
4798        1      2              0.562          0.636          0.562   
18652       1      1              0.737          0.889          0.737   
1894        2      2              0.461          0.524          0.461   

       science_teacher  languages_teacher  guardian  internet  
13057                6                  3         2         1  
3236                 4                  7         1         1  
14942                2                  0         2         1  
1586                 4                  9         1         1  
5455                 1                  8         2         1  
...                ...                ...       ...       ...  
5750                 8                  6         1         1  
13338                2                  6         1         1  
4798                 1                  5         2         1  
18652                2                  5         2         0  
1894                 0                  3         2         1  

[3753 rows x 9 columns]

In [26]:
X_test.columns

Index(['gender', 'caste', 'mathematics_marks', 'english_marks',
       'science_marks', 'science_teacher', 'languages_teacher', 'guardian',
       'internet'],
      dtype='object')

In [27]:
adc=guess(X_test)

[Parallel(n_jobs=3)]: Using backend ThreadingBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done   3 out of   3 | elapsed:    0.0s finished
